kind: pipeline
name: Xenon

clone:
  depth: 1

steps:
- name: Building
  image: fadlyas/kernel_dockerfile
  environment:
    token:
      from_secret: token
  commands:
  - chmod 777 build.sh
  - bash build.sh
